export const SET_USERS = "SET_USERS";
export const SET_ACCOUNTS = "SET_ACCOUNTS";
export const GET_USERINFO = "GET_USERINFO";
export const ADD_USERINFO = "ADD_USERINFO";
export const DELETE_USERINFO = "DELETE_USERINFO";
export const UPDATE_USERINFO = "UPDATE_USERINFO";
export const UPDATE_USERPARTIAL = "UPDATE_USERPARTIAL";
export const ADD_ACCOUNTINFO = "ADD_ACCOUNTINFO";
export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
